/**
 * ONE-TIME SCRIPT — Generate BCrypt hash and insert admin user.
 *
 * HOW TO RUN (from the backend/ directory):
 *   mvn compile exec:java -Dexec.mainClass="CreateAdminRunner" -Dexec.classpathScope=runtime
 *
 * OR simply run the Spring Boot app once with the profile "create-admin":
 *   Just use the SQL below — the hash was generated by Spring BCryptPasswordEncoder.
 */

// This file is documentation only.
// Use create_admin_spring.sql below which has the correct hash.
