#
#server.port=8080
#
#
#app.base-url=http://localhost:8080
#
#spring.datasource.url=jdbc:mysql://localhost:3306/tutorfinder_1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=pass
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#jwt.secret=VGVzdFNlY3JldEtleUZvclR1dG9yRmluZGVyMjAyNEFwcA==
jwt.expiration=86400000
#
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#file.upload-dir=./uploads
#
#razorpay.key.id=rzp_test_XXXXXXXXXXXXXXXX
#razorpay.key.secret=YOUR_RAZORPAY_SECRET
#razorpay.currency=INR
#razorpay.webhook.secret=YOUR_WEBHOOK_SECRET
#
#app.cors.allowed-origins=http://localhost:4200
#
logging.level.com.tutorfinder=DEBUG



server.port=${PORT:8080}
app.base-url=${APP_BASE_URL:http://localhost:8080}

spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:tutorfinder_1}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:pass}

jwt.secret=${JWT_SECRET:VGVzdFNlY3JldEtleUZvclR1dG9yRmluZGVyMjAyNEFwcA==}
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_XXXXXXXXXXXXXXXX}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:YOUR_RAZORPAY_SECRET}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET:YOUR_WEBHOOK_SECRET}

#app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200}
app.cors.allowed-origins=${CORS_ORIGINS:tutor-finder-sooty.vercel.app}
file.upload-dir=${UPLOAD_DIR:./uploads}